# Docker Compose file for development

services:
  # FastAPI application for development
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: rebate-management-api-dev
    ports:
      - "8000:8000"
    environment:
      - APP_NAME=Rebates Management API(Development)
      - APP_VERSION=0.1.0-dev
      - DEBUG=true
      - API_PREFIX=/api/v1
    volumes:
      # Mount source code for hot reload in development
      - .:/app
      # Exclude node_modules and other unnecessary directories
      - /app/__pycache__
      - /app/.ruff_cache
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  
networks:
  default:
    name: rebate-management-network-dev
